/**
 * Modifiers. The first word of the default pattern, as in `stupid`-cunt-head.
 *
 * Sorted, unique, lowercase a-z only. See CONTRIBUTING.md before adding words:
 * profanity and vulgar insults are welcome, slurs are not.
 */
export const ADJECTIVES: readonly string[] = Object.freeze([
  'abhorrent', 'abscessed', 'abysmal', 'addled', 'aggravating', 'angry',
  'appalling', 'arsed', 'arsewiping', 'arsey', 'arsing', 'asinine',
  'atrocious', 'awful', 'ballsed', 'banjaxed', 'barmy', 'bastarding',
  'batty', 'beastly', 'bedraggled', 'befouled', 'begrimed', 'belching',
  'bellowing', 'besmeared', 'bilious', 'blathering', 'bleeding',
  'blistering', 'blithering', 'bloated', 'bloodshot', 'bloodsoaked',
  'bloody', 'blotchy', 'blubbering', 'bodged', 'bogging', 'boggy',
  'bollocking', 'bollocksed', 'bolshy', 'botched', 'braindead', 'brainless',
  'brutish', 'bubbling', 'buggered', 'buggering', 'bulbous', 'bumbling',
  'bungled', 'burbling', 'burping', 'cackhanded', 'cantankerous', 'cheesy',
  'chinless', 'chomping', 'chuffing', 'chundering', 'chundery', 'churlish',
  'clagged', 'clammy', 'clapped', 'clarted', 'clarty', 'clattering',
  'clotted', 'clotting', 'clueless', 'coagulated', 'congealed',
  'congealing', 'contemptible', 'corroded', 'cranky', 'crapping', 'crass',
  'craven', 'crawling', 'creepy', 'cringing', 'cruddy', 'crusted',
  'crusting', 'crusty', 'cunting', 'curdled', 'curdling', 'cursed', 'daft',
  'damnable', 'damned', 'dank', 'dastardly', 'decaying', 'decrepit',
  'defecating', 'defective', 'deplorable', 'depraved', 'derelict',
  'desperate', 'despicable', 'detestable', 'dire', 'discharging',
  'disgraceful', 'disgusting', 'dishevelled', 'dismal', 'disreputable',
  'dissolute', 'distasteful', 'doddering', 'dodgy', 'dopey', 'dozy',
  'dreadful', 'dribbled', 'dribbling', 'dripping', 'drippy', 'drizzling',
  'droopy', 'dunged', 'dungy', 'earwaxed', 'effing', 'eggy', 'emetic',
  'encrusted', 'enraged', 'evacuating', 'excremental', 'excreting',
  'execrable', 'faecal', 'fannying', 'farting', 'fatuous', 'feckless',
  'feeble', 'feral', 'fermented', 'festered', 'festering', 'fetid',
  'filthy', 'fizzing', 'flabby', 'flaccid', 'flaking', 'flatulating',
  'flatulent', 'flyblown', 'foaming', 'foetid', 'foolhardy', 'footling',
  'forsaken', 'foul', 'fouled', 'fraudulent', 'frigging', 'frightful',
  'frothing', 'fucked', 'fucking', 'fumbling', 'fungal', 'furious', 'fusty',
  'galling', 'gangrenous', 'garbled', 'gassy', 'gawping', 'germy',
  'ghastly', 'gibbering', 'gloopy', 'gluey', 'glutinous', 'gnashing',
  'gobby', 'godforsaken', 'goggling', 'gooey', 'goopy', 'gopping',
  'gormless', 'graceless', 'grating', 'greased', 'greasy', 'grimed',
  'grimy', 'gristly', 'grotesque', 'grotty', 'grouchy', 'grubby',
  'gruesome', 'grumpy', 'grunting', 'gungy', 'gunked', 'gunky', 'gurgling',
  'gushing', 'guttural', 'guzzling', 'hairy', 'halfbaked', 'hapless',
  'harebrained', 'harrowing', 'haunted', 'heaving', 'heinous', 'hellish',
  'hideous', 'hissing', 'hopeless', 'horrid', 'howling', 'huffing', 'humid',
  'humming', 'humourless', 'hungover', 'icky', 'ignoble',
  'illiterate', 'impudent', 'inane', 'incompetent', 'indecent', 'indolent',
  'inept', 'infected', 'infernal', 'infested', 'inflamed', 'insipid',
  'insolent', 'insufferable', 'insulting', 'irksome', 'itching',
  'jabbering', 'jaded', 'jangling', 'jittering', 'jizzy', 'jowly',
  'juddering', 'knackered', 'knobbled', 'knobbly', 'knotted',
  'lackadaisical', 'lamentable', 'lardy', 'leaden', 'leaking', 'leaky',
  'leering', 'leprous', 'lethargic', 'listless', 'loathsome', 'lolloping',
  'lousy', 'lumbering', 'lumpy', 'lurching', 'lurid', 'maggoty',
  'malodorous', 'mangled', 'mangy', 'manky', 'maudlin', 'mawkish', 'mealy',
  'measly', 'meddlesome', 'melted', 'mephitic', 'miasmic', 'mildewed',
  'minging', 'mingy', 'miserable', 'misshapen', 'moaning', 'moist',
  'moldering', 'moldy', 'moping', 'mottled', 'mouldering', 'mouldy',
  'mournful', 'mucky', 'muggy', 'mulish', 'munted', 'murky', 'mushy',
  'musty', 'mutinous', 'naff', 'naffing', 'narky', 'nasty', 'nauseating',
  'necrotic', 'nefarious', 'nervy', 'nettled', 'nibbled', 'niffy',
  'nocuous', 'noisome', 'nonsensical', 'noxious', 'numb',
  'obnoxious', 'obscene', 'obstinate', 'obtuse', 'odious', 'offensive',
  'oily', 'oozing', 'ordurous', 'ornery', 'outrageous', 'pallid',
  'pandemonic', 'pasty', 'pathetic', 'peevish', 'perished', 'pernicious',
  'pestering', 'pestilent', 'petulant', 'phlegmy', 'pickled', 'pigging',
  'pilfering', 'pimpled', 'pimply', 'pissed', 'pissing', 'pissy', 'pitiful',
  'plastered', 'plopping', 'pockmarked', 'pointless', 'pompous', 'pongy',
  'poxy', 'preposterous', 'prickly', 'puddled', 'puerile', 'puffy', 'puked',
  'pukey', 'pungent', 'purulent', 'pustular', 'putrefying', 'putrescent',
  'putrid', 'quaking', 'qualmish', 'quarrelsome', 'queasy', 'querulous',
  'quivering', 'rabid', 'raddled', 'ragged', 'raging', 'rancid',
  'rancorous', 'randy', 'rank', 'rasping', 'ratty', 'raucous', 'ravenous',
  'reckless', 'reeking', 'repellent', 'reprehensible', 'repugnant',
  'repulsive', 'retching', 'revolting', 'rheumy', 'ribald', 'rickety',
  'ridiculous', 'roaring', 'rotten', 'rotting', 'rowdy', 'rubbish', 'ruddy',
  'ruinous', 'rumbling', 'rusted', 'sagging', 'salty', 'sanctimonious',
  'scabby', 'scabrous', 'scalding', 'scandalous', 'scathing', 'scattered',
  'scowling', 'scrappy', 'scratchy', 'screeching', 'scruffy', 'scummy',
  'scurfy', 'scurrilous', 'scurvy', 'scuzzy', 'seedy', 'seeping', 'septic',
  'shambolic', 'shameless', 'shat', 'shifty', 'shite', 'shitey',
  'shitfaced', 'shitsmeared', 'shitting', 'shitty', 'shoddy', 'shonky',
  'shouty', 'shrieking', 'shrivelled', 'sickly', 'sicky', 'simpering',
  'sketchy', 'skiddy', 'slack', 'slapdash', 'slatternly',
  'sleazy', 'slimy', 'slipshod', 'slobbering', 'slobbery', 'sloppy',
  'sloshed', 'slovenly', 'sludgy', 'slurred', 'smarmy', 'smeared', 'smelly',
  'smoldering', 'smothered', 'smouldering', 'smudgy', 'snarling',
  'snivelling', 'snoring', 'snotty', 'sodden', 'sodding', 'soggy', 'soiled',
  'sopping', 'sordid', 'sour', 'spattered', 'spewing', 'spiteful',
  'splurging', 'spluttering', 'spoiled', 'spunky', 'squalid', 'squelching',
  'squelchy', 'squinting', 'squirting', 'squittery', 'stagnant', 'stained',
  'stale', 'steaming', 'sticky', 'stinking', 'stroppy', 'stupid', 'sulking',
  'sullen', 'sunken', 'suppurating', 'surly', 'swampy', 'sweaty', 'swollen',
  'tainted', 'tarnished', 'tarry', 'tasteless', 'tatty', 'terrible',
  'thick', 'toothless', 'torrid', 'toxic', 'trampled', 'treacherous',
  'truculent', 'turdy', 'turgid', 'twatted', 'twatting', 'ugly',
  'ulcerated', 'ulcerous', 'unbearable', 'uncouth', 'unctuous', 'underdone',
  'unflushed', 'ungainly', 'unhinged', 'unhygienic', 'unkempt',
  'unpleasant', 'unruly', 'unsanitary', 'unsavoury', 'unseemly',
  'unsightly', 'unspeakable', 'unwashed', 'unwholesome', 'unwiped',
  'urinous', 'useless', 'vacuous', 'vengeful', 'venomous', 'verminous',
  'vexatious', 'vile', 'villainous', 'vomiting', 'vomitous', 'vulgar',
  'wanking', 'wanky', 'wanton', 'warped', 'warty', 'wasted', 'weeping',
  'weevilled', 'wheezing', 'whiffy', 'whingeing', 'whining', 'wilted',
  'wilting', 'witless', 'woeful', 'wonky', 'worthless', 'wretched',
  'wrinkled', 'yammering', 'yappy', 'yeasty', 'yellowed',
]);
