/**
 * Modifiers. The first word of the default pattern, as in `stupid`-cunt-head.
 *
 * Sorted, unique, lowercase a-z only. See CONTRIBUTING.md before adding words:
 * profanity and vulgar insults are welcome, slurs are not.
 */
export const ADJECTIVES: readonly string[] = Object.freeze([
  'abhorrent', 'absurd', 'abysmal', 'addled', 'aggravating', 'anaemic',
  'angry', 'anguished', 'antisocial', 'appalling', 'arsey', 'asinine',
  'atrocious', 'awful', 'baggy', 'balding', 'balmy', 'bandy', 'barmy',
  'batty', 'beastly', 'bedraggled', 'belching', 'bellowing', 'bilious',
  'bitter', 'blathering', 'bleak', 'bleeding', 'blistered', 'blithering',
  'bloated', 'bloody', 'blotchy', 'blubbering', 'bodged', 'boggy', 'boiled',
  'bolshy', 'bonkers', 'botched', 'braindead', 'brainless', 'bristly',
  'broken', 'bruised', 'brutish', 'bubbling', 'bulbous', 'bumbling',
  'bungled', 'burbling', 'burnt', 'cackhanded', 'cackling', 'cantankerous',
  'chapped', 'charmless', 'cheerless', 'chewed', 'chinless', 'chomping',
  'chuffing', 'churlish', 'clammy', 'clapped', 'clarty', 'clattering',
  'clotted', 'cloying', 'clueless', 'clumsy', 'coagulated', 'cobbled',
  'congealed', 'contemptible', 'corroded', 'cracked', 'cranky', 'crass',
  'craven', 'crazed', 'creaking', 'creepy', 'cringing', 'crooked',
  'crumbling', 'crusted', 'crusty', 'cuckoo', 'cursed', 'daft', 'damnable',
  'damp', 'dank', 'dastardly', 'dawdling', 'decaying', 'decrepit',
  'defective', 'deluded', 'demented', 'dense', 'deplorable', 'depraved',
  'derelict', 'desperate', 'despicable', 'detestable', 'dilapidated', 'dim',
  'dingy', 'dire', 'disgraceful', 'disgusting', 'dishevelled', 'dismal',
  'disreputable', 'dissolute', 'distasteful', 'doddering', 'dodgy',
  'dolorous', 'doomed', 'dopey', 'dozy', 'drab', 'dreadful', 'dribbling',
  'drippy', 'droning', 'drooping', 'droopy', 'dull', 'dusty', 'earwaxed',
  'eggy', 'embarrassing', 'enraged', 'evasive', 'execrable', 'farting',
  'fatuous', 'feckless', 'feeble', 'feral', 'fermented', 'festering', 'fetid',
  'filthy', 'fizzing', 'flabby', 'flaccid', 'flaking', 'flatulent', 'flimsy',
  'floundering', 'flustered', 'foaming', 'foetid', 'foolhardy', 'footling',
  'forsaken', 'foul', 'frantic', 'fraudulent', 'frayed', 'frightful',
  'frothing', 'fumbling', 'fungal', 'furious', 'fusty', 'galling',
  'gangrenous', 'garbled', 'gassy', 'gawping', 'ghastly', 'gibbering',
  'glutinous', 'gnarled', 'gnashing', 'goggling', 'gormless', 'graceless',
  'grating', 'greasy', 'grimy', 'gristly', 'grizzled', 'groaning',
  'grotesque', 'grotty', 'grouchy', 'grubby', 'gruesome', 'grumbling',
  'grumpy', 'grunting', 'gummy', 'gungy', 'gunky', 'gurgling', 'gushing',
  'guttural', 'hairy', 'halfbaked', 'hapless', 'harebrained', 'harrowing',
  'haunted', 'heaving', 'heinous', 'hellish', 'hideous', 'hissing',
  'hopeless', 'horrid', 'howling', 'huffing', 'humourless', 'hungover',
  'idiotic', 'ignoble', 'illiterate', 'impudent', 'inane', 'incompetent',
  'indecent', 'indolent', 'inept', 'infernal', 'infested', 'inflamed',
  'insipid', 'insolent', 'insufferable', 'insulting', 'irksome', 'jabbering',
  'jaded', 'jangling', 'jittering', 'jowly', 'juddering', 'knackered',
  'knobbled', 'knotted', 'lackadaisical', 'lamentable', 'lardy', 'leaden',
  'leaking', 'leering', 'lethargic', 'listless', 'loathsome', 'lolloping',
  'loopy', 'lousy', 'lumbering', 'lumpy', 'lurching', 'lurid', 'maggoty',
  'malodorous', 'mangled', 'mangy', 'manky', 'maudlin', 'mawkish', 'mealy',
  'measly', 'meddlesome', 'melted', 'mildewed', 'miserable', 'misshapen',
  'moaning', 'moist', 'moldering', 'moldy', 'moping', 'mottled', 'mouldering',
  'mouldy', 'mournful', 'mucky', 'muddled', 'muggy', 'mulish', 'mumbling',
  'murky', 'mushy', 'musty', 'mutinous', 'naff', 'narky', 'nasty',
  'nauseating', 'nefarious', 'nervy', 'nettled', 'nibbled', 'niggling',
  'nocuous', 'noisome', 'nonsensical', 'noxious', 'numb', 'obnoxious',
  'obscene', 'obstinate', 'obtuse', 'odious', 'offensive', 'oily', 'oozing',
  'ornery', 'outrageous', 'pallid', 'pandemonic', 'pasty', 'pathetic',
  'peevish', 'perished', 'pernicious', 'pestering', 'pestilent', 'petulant',
  'pickled', 'pilfering', 'pimply', 'pitiful', 'plastered', 'pockmarked',
  'pointless', 'pompous', 'pongy', 'poxy', 'prattling', 'preposterous',
  'prickly', 'puerile', 'puffy', 'pungent', 'putrefying', 'putrid', 'quaking',
  'qualmish', 'quarrelsome', 'queasy', 'querulous', 'quivering', 'rabid',
  'raddled', 'ragged', 'raging', 'rambling', 'rancid', 'rancorous', 'randy',
  'rank', 'rasping', 'ratty', 'raucous', 'ravenous', 'reckless', 'reeking',
  'repellent', 'reprehensible', 'repugnant', 'repulsive', 'revolting',
  'ribald', 'rickety', 'ridiculous', 'roaring', 'rotten', 'rotting', 'rowdy',
  'rubbish', 'ruddy', 'ruinous', 'rumbling', 'rusted', 'salty',
  'sanctimonious', 'scabby', 'scalding', 'scandalous', 'scathing',
  'scattered', 'scowling', 'scrappy', 'scratchy', 'screeching', 'scruffy',
  'scummy', 'scurrilous', 'scurvy', 'seedy', 'septic', 'shabby', 'shambolic',
  'shameless', 'shifty', 'shoddy', 'shonky', 'shouty', 'shrieking',
  'shrivelled', 'sickly', 'simpering', 'skanky', 'sketchy', 'slack',
  'slapdash', 'slatternly', 'sleazy', 'slimy', 'slipshod', 'slobbering',
  'sloppy', 'sloshed', 'slovenly', 'sludgy', 'slurred', 'smarmy', 'smelly',
  'smoldering', 'smothered', 'smouldering', 'snarling', 'snivelling',
  'snoring', 'snotty', 'sodden', 'soggy', 'sopping', 'sordid', 'sour',
  'sozzled', 'spiteful', 'spluttering', 'spoiled', 'spongy', 'spotty',
  'sprawling', 'squalid', 'squelchy', 'squiffy', 'squinting', 'stagnant',
  'stained', 'stale', 'stammering', 'steaming', 'stinking', 'stroppy',
  'stuffy', 'stupefied', 'stupid', 'sulking', 'sullen', 'sunken', 'surly',
  'swampy', 'sweaty', 'swollen', 'tacky', 'tainted', 'tangled', 'tarnished',
  'tasteless', 'tattered', 'tatty', 'tedious', 'teetering', 'tepid',
  'terrible', 'thankless', 'thick', 'thoughtless', 'thundering', 'tiresome',
  'toothless', 'torrid', 'tottering', 'trampled', 'treacherous', 'tremulous',
  'truculent', 'tumbledown', 'turgid', 'twisted', 'ugly', 'unbearable',
  'uncouth', 'unctuous', 'underdone', 'ungainly', 'unhinged', 'unkempt',
  'unpleasant', 'unravelled', 'unruly', 'unsavoury', 'unseemly', 'unsightly',
  'unspeakable', 'unsteady', 'untidy', 'unwashed', 'unwholesome', 'useless',
  'vacant', 'vacuous', 'vengeful', 'venomous', 'verminous', 'vexatious',
  'vile', 'villainous', 'vulgar', 'waffling', 'wailing', 'wanton', 'warped',
  'warty', 'wasted', 'wayward', 'weeping', 'weevilled', 'weird', 'wheezing',
  'whiffy', 'whimpering', 'whingeing', 'whining', 'wilted', 'wilting',
  'windy', 'witless', 'wobbly', 'woeful', 'wonky', 'woolly', 'worthless',
  'wretched', 'wrinkled', 'yammering', 'yappy', 'yawning', 'yeasty',
  'yellowed', 'zonked',
]);
