/**
 * The rude core of the phrase, as in stupid-`cunt`-head.
 *
 * Sorted, unique, lowercase a-z only. See CONTRIBUTING.md before adding words:
 * profanity and vulgar insults are welcome, slurs are not.
 */
export const NOUNS: readonly string[] = Object.freeze([
  'arse', 'arsebadger', 'arsebiscuit', 'arseclown', 'arsehole',
  'arsemonger', 'arsepiece', 'arsewipe', 'arsewit', 'ass', 'asshat',
  'asshole', 'ballbag', 'ballsack', 'bampot', 'bastard', 'bawbag', 'beggar',
  'bellend', 'berk', 'bilewater', 'bilge', 'blaggard', 'blather',
  'blighter', 'blister', 'blowhard', 'bludger', 'bogey', 'boil', 'bollock',
  'bollocks', 'bonehead', 'boob', 'boofhead', 'booger', 'bounder', 'bozo',
  'brute', 'buffoon', 'bugger', 'bum', 'bumcrack', 'bumfluff', 'bumhole',
  'bumwad', 'bunghole', 'butt', 'buttock', 'cack', 'cad', 'carbuncle',
  'charlatan', 'chode', 'chowderhead', 'chuff', 'chump', 'clacker', 'clod',
  'clodhopper', 'clot', 'clown', 'clunge', 'cobblers', 'cock', 'cockend',
  'cockhead', 'cocknose', 'cockrot', 'cockspanner', 'cockstain',
  'cockwaffle', 'cockwomble', 'codger', 'codpiece', 'coot', 'crackpot',
  'crank', 'crap', 'crapbag', 'craphead', 'craphole', 'crapsack', 'creep',
  'crotch', 'crud', 'cunt', 'cuntflap', 'cunthead', 'cuntpuffin', 'cuntrag',
  'cuntwaffle', 'cur', 'curmudgeon', 'cyst', 'dafty', 'dickbag',
  'dickcheese', 'dickhead', 'dickrot', 'dicksplash', 'dickstain', 'dickwad',
  'dickweed', 'dickwit', 'dingbat', 'dingleberry', 'dipstick', 'dobber',
  'dogsbody', 'dolt', 'donkey', 'dork', 'dosser', 'douche', 'douchebag',
  'douchecanoe', 'dreck', 'dribble', 'drip', 'drivel', 'drongo', 'dropkick',
  'dross', 'dunce', 'dungheap', 'earwax', 'eejit', 'effluent', 'excrement',
  'fanny', 'fart', 'fartbag', 'farthead', 'fartknocker', 'fathead', 'feck',
  'fecker', 'filth', 'flange', 'flapdoodle', 'flatus', 'fool', 'fop',
  'fraud', 'frump', 'fuck', 'fuckbag', 'fuckbucket', 'fuckface', 'fuckhead',
  'fucknuckle', 'fucknugget', 'fuckpuddle', 'fuckstick', 'fucktrumpet',
  'fuckwad', 'fuckwit', 'fungus', 'funk', 'galoot', 'gasbag', 'gash', 'git',
  'glob', 'globule', 'gob', 'gobdaw', 'goblin', 'gobshite', 'gonad', 'gonk',
  'goo', 'goober', 'goon', 'goop', 'grease', 'grifter', 'grime', 'grot',
  'grouch', 'grub', 'grump', 'guano', 'guff', 'gump', 'gunge', 'gunk',
  'guts', 'gutter', 'hack', 'heap', 'heel', 'helmet', 'herbert', 'hogwash',
  'hooligan', 'horror', 'huckster', 'humbug', 'hump', 'ingrate', 'jackass',
  'jerk', 'jizz', 'jizzbag', 'jizzrag', 'jobby', 'junk', 'klutz', 'knacker',
  'knackers', 'knave', 'knob', 'knobend', 'knobhead', 'knucklehead',
  'lackey', 'langer', 'layabout', 'leech', 'lice', 'loafer', 'loudmouth',
  'lout', 'lowlife', 'lug', 'lummox', 'lump', 'lurgy', 'maggot', 'mange',
  'manure', 'meathead', 'melt', 'menace', 'mess', 'minge', 'miscreant',
  'moocher', 'muck', 'mucus', 'mug', 'muppet', 'mush', 'mutt', 'nag',
  'nerk', 'nincompoop', 'ninny', 'nitwit', 'nobber', 'numbnut', 'numbnuts',
  'numbskull', 'numpty', 'nutsack', 'oaf', 'ogre', 'oik', 'ooze', 'ordure',
  'parasite', 'peabrain', 'pest', 'phlegm', 'pillock', 'pipsqueak', 'piss',
  'pissbag', 'pissflaps', 'pisshead', 'pisspot', 'pissweasel', 'plank',
  'plonker', 'poltroon', 'pong', 'poop', 'poot', 'prat', 'prick', 'puke',
  'punk', 'pus', 'pustule', 'quack', 'rapscallion', 'rascal', 'rash', 'rat',
  'ratbag', 'reprobate', 'reptile', 'ringpiece', 'roaster', 'rogue', 'rot',
  'rotter', 'rubbish', 'ruffian', 'runt', 'scab', 'scallywag', 'scamp',
  'schlub', 'scoundrel', 'scourge', 'scrag', 'screwball', 'scrote',
  'scrotum', 'scrub', 'scruff', 'scum', 'scumbag', 'scurf', 'sewage',
  'shambles', 'shirker', 'shit', 'shitbag', 'shitbrain', 'shite',
  'shitehawk', 'shitface', 'shitgibbon', 'shitheap', 'shitheel',
  'shitkicker', 'shitmuncher', 'shitrag', 'shitstain', 'shitstick',
  'shitweasel', 'shyster', 'skid', 'skidmark', 'skunk', 'slacker', 'sleaze',
  'slob', 'sloth', 'sludge', 'slug', 'slurry', 'smear', 'smegma', 'snake',
  'snitch', 'snivel', 'snot', 'sod', 'spanner', 'spew', 'splodge',
  'splurge', 'sponge', 'spunk', 'spunkbag', 'spunkbubble', 'spunktrumpet',
  'sputum', 'squib', 'stench', 'stinker', 'stooge', 'sty', 'swindler',
  'swine', 'testicle', 'thicko', 'thug', 'tit', 'toad', 'toerag', 'toff',
  'toilet', 'tomfool', 'tosser', 'tosspot', 'turd', 'turdburger',
  'turdface', 'turdnugget', 'turdrocket', 'twat', 'twatbadger', 'twatface',
  'twathead', 'twatnugget', 'twatwaffle', 'twerp', 'twit', 'twonk',
  'vagabond', 'varmint', 'vermin', 'villain', 'vomit', 'vulture', 'wally',
  'wank', 'wanker', 'wankpuffin', 'wankstain', 'wankweasel', 'wart',
  'wastrel', 'wazzock', 'weapon', 'weasel', 'weirdo', 'wetwipe', 'whelp',
  'windbag', 'wingnut', 'worm', 'wretch', 'yob', 'yokel',
]);
