/**
 * The rude core of the phrase, as in stupid-`cunt`-head.
 *
 * Sorted, unique, lowercase a-z only. See CONTRIBUTING.md before adding words:
 * profanity and vulgar insults are welcome, slurs are not.
 */
export const NOUNS: readonly string[] = Object.freeze([
  'arse', 'arsehole', 'arsewipe', 'ass', 'asshat', 'asshole', 'badger',
  'bampot', 'bandit', 'barnacle', 'bastard', 'beggar', 'bellend', 'berk',
  'bilge', 'blaggard', 'blather', 'blighter', 'blister', 'blowhard',
  'bludger', 'blunder', 'bogey', 'boil', 'bollock', 'bollocks', 'bonce',
  'bonehead', 'boob', 'booger', 'bottom', 'bounder', 'bozo', 'brute',
  'buffoon', 'bugger', 'bum', 'bumhole', 'bunghole', 'butt', 'buttock',
  'cack', 'cackle', 'cad', 'caper', 'carbuncle', 'charlatan', 'chode',
  'chomp', 'chops', 'chowderhead', 'chump', 'clacker', 'clanger', 'clod',
  'clodhopper', 'clot', 'clown', 'clunge', 'cobblers', 'cock', 'cockwomble',
  'codger', 'codpiece', 'coot', 'crackpot', 'crank', 'creep', 'crotch',
  'crumb', 'crust', 'cur', 'curmudgeon', 'cyst', 'dafty', 'dingbat',
  'dingleberry', 'dipstick', 'divot', 'dogsbody', 'dolt', 'dongle', 'donkey',
  'dork', 'dosser', 'douche', 'douchebag', 'drain', 'dribble', 'drip',
  'drivel', 'droop', 'dross', 'dunce', 'dungheap', 'earwax', 'eejit',
  'fandango', 'fanny', 'fart', 'fathead', 'fiddle', 'filth', 'flange', 'flap',
  'flapdoodle', 'flea', 'flimflam', 'flop', 'fluff', 'foghorn', 'fool', 'fop',
  'fraud', 'frump', 'fuddle', 'fungus', 'funk', 'gasbag', 'gash', 'git',
  'gizzard', 'glob', 'globule', 'gnat', 'gob', 'goblin', 'gonk', 'goo',
  'goober', 'goon', 'goop', 'grease', 'gremlin', 'grifter', 'grime', 'gripe',
  'grot', 'grouch', 'grub', 'grump', 'guff', 'gullet', 'gump', 'gunge',
  'gunk', 'guts', 'gutter', 'hack', 'hamper', 'hazard', 'heap', 'heel',
  'hobgoblin', 'hogwash', 'hooligan', 'horror', 'huckster', 'humbug', 'hump',
  'ingrate', 'jabber', 'jackass', 'jalopy', 'jerk', 'jitter', 'jobby',
  'jumble', 'junk', 'kipper', 'klutz', 'knacker', 'knave', 'knob', 'knobend',
  'knobhead', 'knucklehead', 'lackey', 'layabout', 'leech', 'lemon', 'lice',
  'loafer', 'loon', 'loudmouth', 'lout', 'lowlife', 'lug', 'lummox', 'lump',
  'lurgy', 'maggot', 'mange', 'meathead', 'menace', 'mess', 'miscreant',
  'mishap', 'mogul', 'moocher', 'mouth', 'muck', 'mucus', 'muddle', 'mug',
  'mule', 'mungo', 'muppet', 'mush', 'mushroom', 'mutt', 'muzzle', 'nag',
  'natter', 'nerk', 'nincompoop', 'ninny', 'nipper', 'nitwit', 'noodle',
  'numbnut', 'numbskull', 'numpty', 'nutter', 'oaf', 'ogre', 'oik', 'ooze',
  'pancake', 'pants', 'parasite', 'peabrain', 'pest', 'pickle', 'pillock',
  'pipsqueak', 'plank', 'plonker', 'poltroon', 'pong', 'poop', 'poot',
  'porridge', 'prat', 'prattle', 'prick', 'prune', 'pudding', 'puddle',
  'puffball', 'pumpkin', 'punk', 'pustule', 'quack', 'quagmire', 'quibble',
  'racket', 'rapscallion', 'rascal', 'rash', 'rat', 'rattle', 'reprobate',
  'reptile', 'rind', 'ringpiece', 'rogue', 'rot', 'rotter', 'rubbish',
  'ruffian', 'runt', 'rustler', 'sausage', 'scab', 'scallywag', 'scamp',
  'scatter', 'schlub', 'scoundrel', 'scourge', 'scrag', 'scrap', 'scratch',
  'screwball', 'scrote', 'scrub', 'scruff', 'scum', 'scumbag', 'scurf',
  'shambles', 'shindig', 'shirker', 'shitbag', 'shitheap', 'shitheel',
  'shocker', 'shrimp', 'shyster', 'simpleton', 'skid', 'skunk', 'slacker',
  'sleaze', 'slob', 'sloth', 'sludge', 'slug', 'slurry', 'smear', 'smudge',
  'snail', 'snake', 'snitch', 'snivel', 'snot', 'sod', 'sop', 'spanner',
  'spat', 'splatter', 'splodge', 'splurge', 'sponge', 'spud', 'squabble',
  'squib', 'stench', 'stinker', 'stoat', 'stooge', 'stumble', 'sty', 'swamp',
  'swindler', 'swine', 'tantrum', 'thicko', 'thug', 'tick', 'tit', 'toad',
  'toadstool', 'toerag', 'toff', 'toilet', 'tomfool', 'tosser', 'tosspot',
  'trout', 'truant', 'tuber', 'turd', 'turnip', 'twerp', 'twit', 'twonk',
  'urchin', 'vagabond', 'varmint', 'vermin', 'villain', 'vulture', 'waffle',
  'wally', 'wart', 'wastrel', 'weasel', 'weevil', 'weirdo', 'welk', 'wetwipe',
  'whelk', 'whelp', 'whiffle', 'windbag', 'wingnut', 'worm', 'wretch', 'yob',
  'yokel', 'zealot',
]);
