/**
 * Insult tails. The last word of the default pattern, as in stupid-cunt-`head`.
 *
 * Sorted, unique, lowercase a-z only. See CONTRIBUTING.md before adding words:
 * profanity and vulgar insults are welcome, slurs are not.
 */
export const SUFFIXES: readonly string[] = Object.freeze([
  'admiral', 'ape', 'badger', 'baffler', 'bag', 'bagpipe', 'bandit', 'bane',
  'baron', 'basher', 'basket', 'beacon', 'beak', 'beard', 'bellows',
  'bidet', 'bin', 'biscuit', 'bishop', 'blaster', 'blender', 'blister',
  'blossom', 'bollard', 'bonnet', 'botherer', 'bottler', 'bouncer', 'bowl',
  'brain', 'breath', 'brigade', 'broth', 'bucket', 'bugle', 'burger',
  'burglar', 'button', 'cabbage', 'cactus', 'cake', 'canoe', 'captain',
  'casserole', 'cauldron', 'chariot', 'chaser', 'chimney', 'chomper',
  'chops', 'chowder', 'chucker', 'chugger', 'churner', 'cistern', 'clanger',
  'clencher', 'clobberer', 'clown', 'cluster', 'cobbler', 'colander',
  'colonel', 'commander', 'commode', 'crumpet', 'crusader', 'crusher',
  'cudgel', 'custard', 'cutlet', 'dangler', 'dodger', 'doodle', 'drainpipe',
  'dribbler', 'drizzle', 'duke', 'dumpling', 'dungeon', 'dunker', 'emperor',
  'engine', 'fancier', 'ferret', 'fiddler', 'flannel', 'flapjack',
  'flapper', 'flinger', 'fondler', 'fountain', 'fucker', 'fumbler',
  'funnel', 'gargler', 'general', 'gherkin', 'gibbon', 'gnawer', 'gobbler',
  'goblin', 'goose', 'grabber', 'grappler', 'gravy', 'gremlin', 'grinder',
  'grumbler', 'gusset', 'guzzler', 'hammer', 'hamper', 'hamster', 'handler',
  'harvester', 'head', 'herder', 'hoarder', 'hogger', 'honker', 'hopper',
  'hornet', 'hound', 'howitzer', 'huffer', 'hunter', 'hurler', 'inspector',
  'jangler', 'jester', 'jockey', 'jostler', 'juggler', 'juicer', 'kazoo',
  'kettle', 'kipper', 'knight', 'knuckle', 'lantern', 'latrine', 'licker',
  'lobber', 'lobster', 'lord', 'machine', 'magnet', 'major', 'mangler',
  'marmalade', 'marshal', 'masher', 'mauler', 'mayor', 'meringue', 'mincer',
  'minister', 'moaner', 'monger', 'mongoose', 'monkey', 'mop', 'mouth',
  'muffin', 'mumbler', 'muncher', 'mushroom', 'newt', 'nibbler', 'noodle',
  'nozzle', 'nugget', 'nuzzler', 'otter', 'outhouse', 'pamphlet', 'pancake',
  'pants', 'parade', 'parsnip', 'peddler', 'pelican', 'pelter', 'pickle',
  'pigeon', 'pilferer', 'pilot', 'pincher', 'pirate', 'platypus', 'plodder',
  'plopper', 'plunger', 'poker', 'polisher', 'pope', 'potato', 'pouch',
  'pounder', 'privy', 'prodder', 'puddle', 'puffin', 'pump', 'pumpkin',
  'puncher', 'rabbit', 'rambler', 'rattler', 'rocket', 'romper', 'rooster',
  'rummager', 'rustler', 'salamander', 'sandwich', 'sausage', 'scoffer',
  'scone', 'scooper', 'scraper', 'sergeant', 'shackle', 'shagger',
  'sheriff', 'shovel', 'shuffler', 'sieve', 'sifter', 'skittle', 'slinger',
  'sloucher', 'slug', 'slurper', 'smacker', 'smuggler', 'snaffler', 'snail',
  'sniffer', 'snorkel', 'snorter', 'socket', 'soup', 'spanker', 'spanner',
  'spigot', 'splasher', 'splatter', 'sponge', 'spoon', 'sprayer',
  'sprocket', 'squeezer', 'squelcher', 'squid', 'squire', 'stain', 'stew',
  'stick', 'stirrer', 'stomper', 'strangler', 'stuffer', 'sucker', 'sultan',
  'swiller', 'tackler', 'thistle', 'thumper', 'tickler', 'tinkler', 'toad',
  'toaster', 'tombola', 'tootler', 'torpedo', 'trickler', 'trombone',
  'trotter', 'trough', 'trout', 'trumpet', 'tugger', 'tumbler', 'turbine',
  'turnip', 'twiddler', 'urinal', 'vestibule', 'vicar', 'wafer', 'waffle',
  'wafter', 'waggler', 'wagon', 'walloper', 'walrus', 'wanker', 'warden',
  'warlock', 'weasel', 'weevil', 'whacker', 'wheelbarrow', 'whisperer',
  'whistle', 'whittler', 'windsock', 'wizard', 'wobbler', 'wombat',
  'wrangler', 'wrestler', 'yanker', 'yapper', 'yodeller',
]);
